AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:
  S3CopyFile:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: s3_copy_file_dotnet
      ContentUri: .
      CompatibleRuntimes:
        - dotnet8
      CompatibleArchitectures:
        - x86_64
      RetentionPolicy: Retain
    Metadata:
      BuildMethod: makefile
  TestBucket:
    Type: AWS::S3::Bucket
  TestLambda:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./functions
      Handler: functions::functions.Test::Handler
      Runtime: dotnet8
      MemorySize: 512
      Timeout: 30
      Layers:
        - !Ref S3CopyFile
      Environment:
        Variables:
          S3_BUCKET: !Ref TestBucket
          S3_KEY: test.txt
      Policies:
        - S3ReadPolicy:
            BucketName: !Ref TestBucket